### PR TITLE
Adds retina-friendly favicon.

### PR DESCRIPTION
**Pull request by charliepark**

### CODE REVIEW

**Comment by charliepark** [comment]
@ginatrapani Here's the refreshed favicon. I also updated another asset in the same folder (docs/source/thinkup-logo_200.png), though I'm not sure if that's one you actually use or not.

Anyway, here you go! Have a great week!

**Comment by charliepark** [comment]
For posterity, here's a before/after: 
screen shot 2015-02-15 at 6 33 40 pm

**Comment by ginatrapani** [comment]
Awesome, thank you so very much!

**Comment by ginatrapani** [comment]
Merged in bea18b41c0e11c98ea1fe4c5ddb1ea6c66c1da9f  Thanks again!

**Pull request closed without merging**
